id: I8DD91F82
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T11:41:45+00:00'
last_modified: '2022-06-07T15:21:07.384760+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN6546
  title: མེ་ཏོག་ལྟ་བུའི་ནམ་ཟླ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedTemporarily
  restrictedInChina: false
  base:
    01D1:
      image_group_id: I3CN6548
      title: ''
      total_pages: 276
      order: 1
      base_file: 01D1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
